apiVersion: v1
kind: Secret
metadata:
  name: logstash-secret
type: Opaque
data:
  XPACK_MANAGEMENT_ELASTICSEARCH_URL: WFBBQ0tfTUFOQUdFTUVOVF9FTEFTVElDU0VBUkNIX1VSTA==
  XPACK_MONITORING_ELASTICSEARCH_URL: WFBBQ0tfTU9OSVRPUklOR19FTEFTVElDU0VBUkNIX1VSTA==
  XPACK_MANAGEMENT_ELASTICSEARCH_USERNAME: WFBBQ0tfTUFOQUdFTUVOVF9FTEFTVElDU0VBUkNIX1VTRVJOQU1F
  XPACK_MONITORING_ELASTICSEARCH_USERNAME: WFBBQ0tfTU9OSVRPUklOR19FTEFTVElDU0VBUkNIX1VTRVJOQU1F
  XPACK_MANAGEMENT_ELASTICSEARCH_PASSWORD: WFBBQ0tfTUFOQUdFTUVOVF9FTEFTVElDU0VBUkNIX1BBU1NXT1JE
  XPACK_MONITORING_ELASTICSEARCH_PASSWORD: WFBBQ0tfTU9OSVRPUklOR19FTEFTVElDU0VBUkNIX1BBU1NXT1JE